### ISSUE TITLE
go build server/server.go does not work

### ISSUE THREAD

**Issue by lynnchae** [postwoman-io/postwoman-proxy#3] opened 2019-12-19 11:05 UTC
go build server/server.go does not work on linux server

**Comment by NBTX** [comment] 2019-12-19 12:18
Odd... What errors are you getting?

**Comment by lynnchae** [comment] 2019-12-19 12:29
it just hang up and nothing print in the console
![image](https://user-images.githubusercontent.com/9653540/71173663-453ca180-229e-11ea-8655-74b1c6f7cdfe.png)

**Comment by NBTX** [comment] 2019-12-19 13:34
I've pushed up some changes to improve the build tooling - which may have fixed these issues anyhow.
Try pulling the changes and running `./build.sh linux server`.

**Comment by NBTX** [comment] 2019-12-24 15:01
Closing under the assumption that the issue is now fixed. If anyone experiences this issue again, leave another comment and I'll reopen the issue.

**Closed by NBTX** 2019-12-24 15:01 UTC
Labels: bug
